services:
  web:
    image: nginx:latest
    container_name: 2264-web
    networks:
      - nginx-docker
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped

networks:
  nginx-docker:
    external: true
