server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;
    error_page 404 /404.html;

    location / {
        ssi on;
        try_files $uri.html $uri $uri/ =404;
    }

    location /components/ {
        internal;
    }

    location /src/ {
        alias /usr/share/nginx/html/src/;
        autoindex on;
        autoindex_exact_size off;
        autoindex_localtime on;
        autoindex_format html;

        if ($request_filename ~ \.(txt|pdf|zip|rar|7z|tar|gz|bat|exe|iso)$) {
            add_header Content-Disposition "attachment";
        }

        add_before_body /autoindex/header.html;
        add_after_body /autoindex/footer.html;

        default_type text/html;
        charset utf-8;

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS" always;
        add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range" always;

        if ($request_method = 'OPTIONS') {
            add_header Access-Control-Allow-Origin "*";
            add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
            add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range";
            add_header Access-Control-Max-Age 1728000;
            add_header Content-Type "text/plain; charset=utf-8";
            add_header Content-Length 0;
            return 204;
        }
    }
}
