# Use the official Nginx image
FROM nginx:alpine

# Copy your static files into the default Nginx HTML directory
COPY . /usr/share/nginx/html

# Expose ports 80 and 443 for HTTP and HTTPS
EXPOSE 80 443
